package org.egov.edcr.constants;

public class DocumentConstants {
	
	public static final String DOC_TYPES_1="DocTypes1";
	public static final String DOC_TYPES_2="DocTypes2";
	public static final String DOC_TYPES_3="DocTypes3";
	public static final String DOC_TYPES_4="DocTypes4";
	public static final String DOC_TYPES_5="DocTypes5";
	public static final String DOC_TYPES_6="DocTypes6";
	public static final String DOC_TYPES_7="DocTypes7";//writen in xsl DocTypes3
	
	public static final String DOC_OSHB_OR_GA_OR_BDA_DEVELOPED_AND_ALLOTTED_PLOT="DOC_OSHB_OR_GA_OR_BDA_DEVELOPED_AND_ALLOTTED_PLOT";
	public static final String DOC_PLOT_PART_OF_APPROVED_PRIVATE_LAYOUT="DOC_PLOT_PART_OF_APPROVED_PRIVATE_LAYOUT";
	public static final String DOC_DOES_PROJECT_REQUIRE_RERA_REGISTRATION="DOC_DOES_PROJECT_REQUIRE_RERA_REGISTRATION";
	public static final String DOC_PLOT_PART_OF_UNAUTHORISED_LAYOUT_OR_REVENUE_PLOT="DOC_PLOT_PART_OF_UNAUTHORISED_LAYOUT_OR_REVENUE_PLOT";
	public static final String DOC_IS_PROJECT_COMING_UNDER_THE_JURISDICTION_OF_PLANNING_AUTHORITIES="DOC_IS_PROJECT_COMING_UNDER_THE_JURISDICTION_OF_PLANNING_AUTHORITIES";
	public static final String DOC_DOES_THE_PROJECT_HAVE_AFFORDABLE_HOUSING_COMPONENT="DOC_DOES_THE_PROJECT_HAVE_AFFORDABLE_HOUSING_COMPONENT";
	public static final String DOC_DOES_THE_PROJECT_HAVE_MORE_THAN_500_SQM_BUILT_UP_AREA_EXCLUDING_THE_AFFORDABLE_HOUSING_COMPONENT="DOC_DOES_THE_PROJECT_HAVE_MORE_THAN_500_SQM_BUILT_UP_AREA_EXCLUDING_THE_AFFORDABLE_HOUSING_COMPONENT";
}
