package org.egov.edcr.constants;

public class NOCConstants {
	
	public static final String OSHB_OR_DEVELOPMENT_AUTHORITY_NOC="OSHB_OR_DEVELOPMENT_AUTHORITY_NOC";
	public static final String DEPUTY_FORST_OFFICEER_NOC="DEPUTY_FORST_OFFICEER_NOC";
	public static final String AAI_NOC="AAI_NOC";
	public static final String NMA_NOC="NMA_NOC";
	public static final String STATE_ARCHAEOLOGY="STATE_ARCHAEOLOGY";
	public static final String ENVIRONMENT_CLEARANCE_NOC="ENVIRONMENT_CLEARANCE_NOC";
	public static final String FIRE_SERVICE_NOC="FIRE_SERVICE_NOC";
	public static final String URBAN_LOCAL_BODIES_UNDER_H_AND_UD_NOC="URBAN_LOCAL_BODIES_UNDER_H_&_UD_NOC";
	public static final String PUBLIC_HEALTH_ENGINEERING_ORGANIZATION_NOC="PUBLIC_HEALTH_ENGINEERING_ORGANIZATION_NOC";
	public static final String CENTRAL_GROUND_WATER_AUTHORITY_NOC="CENTRAL_GROUND_WATER_AUTHORITY_NOC";
	public static final String ELECTRICITY_DISTRIBUTION_COMPANY_NOC="ELECTRICITY_DISTRIBUTION_COMPANY_NOC";
	public static final String POLICE_UNDER_HOME_DEPARTMENT_NOC="POLICE_UNDER_HOME_DEPARTMENT_NOC";
	public static final String WATER_RESOURCES_DEPARTMENT_NOC="WATER_RESOURCES_DEPARTMENT_NOC";
	public static final String ODISHA_STATE_POLLUTION_CONTROL_BOARD_NOC="ODISHA_STATE_POLLUTION_CONTROL_BOARD_NOC";
	public static final String TEHSILDAR_OF_CONCERNED_MOUZA_UNDER_REVENUE_AND_DISASTER_MANGEMENT_NOC="TEHSILDAR_OF_CONCERNED_MOUZA_UNDER_REVENUE__&DISASTER_MANGEMENT_NOC";
	public static final String NHAI_NOC="NHAI_NOC";
	public static final String COASTAL_REGULATION_NOC="COASTAL_REGULATION_NOC";
	
}
